spring:
  redis:
    database: 0
    host: 192.168.0.105
    port: 6379
    connect-timeout: 30S
    lettuce:  # 连接池
      pool:
        max-active: 8 # 最大连接数
        max-wait: -1  # 最大阻塞等待时间(负数表示没限制)
        min-idle: 0   # 最小空闲
        max-idle: 8   # 最大空闲