spring:
  data:
    mongodb:
      # 参考： https://mongodb.net.cn/manual/reference/connection-string/
      # mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
      # options选项
        # 超时选项
          # socketTimeoutMS: 尝试超时之前在套接字上尝试发送或接收的时间（以毫秒为单位）。默认值是永不超时，尽管不同的驱动程序可能有所不同
          # connectTimeoutMS：超时之前尝试连接的时间（以毫秒为单位）。默认值是永不超时，尽管不同的驱动程序可能有所不同
        # 连接池选项
          # maxPoolSize：连接池中的最大连接数。默认值为100
          # minPoolSize: 连接池中的最小连接数。默认值为0
          # maxIdleTimeMS：在删除和关闭连接之前，连接在池中可以保持空闲状态的最大毫秒数
          # waitQueueMultiple：驱动程序将maxPoolSize 值乘以的数字，以提供允许最大数量的线程等待连接从池中可用。有关默认值，请参见/ drivers 文档。
          # waitQueueTimeoutMS: 线程可以等待连接可用的最长时间（以毫秒为单位）。有关默认值，请参见 / drivers文档。
      uri: mongodb://localhost:27017/ok?connectTimeoutMS=300000&maxPoolSize=120
      auto-index-creation: true # 默认为false,不会自动创建索引
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # 打印nosql查询日志